(require 'test/common)


(ert-deftest eldev-stable/unstable-1 ()
  (let ((eldev--test-project "project-h"))
    (eldev--test-delete-cache)
    (eldev--test-run nil ("version" "dependency-a")
      (should (string= stdout "dependency-a 1.0\n"))
      (should (= exit-code 0)))))

(ert-deftest eldev-stable/unstable-2 ()
  (let ((eldev--test-project "project-h"))
    (eldev--test-delete-cache)
    (eldev--test-run nil ("--unstable" "version" "dependency-a")
      (should (string= stdout "dependency-a 1.1\n"))
      (should (= exit-code 0)))))

;; Even if stable and unstable archives have the same priority, Eldev
;; has to respect `eldev-prefer-stable-archives'.
(ert-deftest eldev-stable/unstable-3 ()
  (let ((eldev--test-project "missing-dependency-a"))
    (eldev--test-delete-cache)
    (eldev--test-run nil ("--setup" `(eldev-use-package-archive '(:stable   ("archive-a" . ,(expand-file-name "../package-archive-a"))
                                                                  :unstable ("archive-b" . ,(expand-file-name "../package-archive-b")))
                                                                '(0 . 0))
                          "version" "dependency-a")
      (should (string= stdout "dependency-a 1.0\n"))
      (should (= exit-code 0)))))

(ert-deftest eldev-stable/unstable-4 ()
  (let ((eldev--test-project "missing-dependency-a"))
    (eldev--test-delete-cache)
    (eldev--test-run nil ("--setup" `(eldev-use-package-archive '(:stable   ("archive-a" . ,(expand-file-name "../package-archive-a"))
                                                                  :unstable ("archive-b" . ,(expand-file-name "../package-archive-b")))
                                                                '(0 . 0))
                          "--unstable" "version" "dependency-a")
      (should (string= stdout "dependency-a 1.1\n"))
      (should (= exit-code 0)))))


(ert-deftest eldev-stable/unstable-upgrade-1 ()
  (let ((eldev--test-project "project-h"))
    (eldev--test-delete-cache)
    (eldev--test-run nil ("version" "dependency-a")
      (should (string= stdout "dependency-a 1.0\n"))
      (should (= exit-code 0)))
    (eldev--test-run nil ("upgrade")
      (should (string= stdout "All dependencies are up-to-date\n"))
      (should (= exit-code 0)))
    (eldev--test-run nil ("version" "dependency-a")
      (should (string= stdout "dependency-a 1.0\n"))
      (should (= exit-code 0)))
    (eldev--test-run nil ("--unstable" "upgrade")
      (should (string= stdout "Upgraded or installed 1 dependency package\n"))
      (should (= exit-code 0)))
    (eldev--test-run nil ("version" "dependency-a")
      (should (string= stdout "dependency-a 1.1\n"))
      (should (= exit-code 0)))))

(ert-deftest eldev-stable/unstable-upgrade-2 ()
  (let ((eldev--test-project "project-h"))
    (eldev--test-delete-cache)
    (eldev--test-run nil ("--unstable" "version" "dependency-a")
      (should (string= stdout "dependency-a 1.1\n"))
      (should (= exit-code 0)))
    (eldev--test-run nil ("upgrade")
      (should (string= stdout "All dependencies are up-to-date\n"))
      (should (= exit-code 0)))
    (eldev--test-run nil ("version" "dependency-a")
      (should (string= stdout "dependency-a 1.1\n"))
      (should (= exit-code 0)))
    ;; It should be possible to downgrade back to the stable version with an option.
    (eldev--test-run nil ("upgrade" "--downgrade")
      (should (string= stdout "Upgraded or installed 1 dependency package\n"))
      (should (= exit-code 0)))
    (eldev--test-run nil ("version" "dependency-a")
      (should (string= stdout "dependency-a 1.0\n"))
      (should (= exit-code 0)))))


(provide 'test/archives)
