(require 'test/common)


(ert-deftest eldev-stable/unstable-1 ()
  (let ((eldev--test-project "project-h"))
    (eldev--test-delete-cache)
    (eldev--test-run nil ("version" "dependency-a")
      (should (string= stdout "dependency-a 1.0\n"))
      (should (= exit-code 0)))))

(ert-deftest eldev-stable/unstable-2 ()
  (let ((eldev--test-project "project-h"))
    (eldev--test-delete-cache)
    (eldev--test-run nil ("--unstable" "version" "dependency-a")
      (should (string= stdout "dependency-a 1.1\n"))
      (should (= exit-code 0)))))

;; Even if stable and unstable archives have the same priority, Eldev
;; has to respect `eldev-prefer-stable-archives'.
(ert-deftest eldev-stable/unstable-3 ()
  (let ((eldev--test-project "missing-dependency-a"))
    (eldev--test-delete-cache)
    (eldev--test-run nil ("--setup" `(eldev-use-package-archive '(:stable   ("archive-a" . ,(expand-file-name "../package-archive-a"))
                                                                  :unstable ("archive-b" . ,(expand-file-name "../package-archive-b")))
                                                                '(0 . 0))
                          "version" "dependency-a")
      (should (string= stdout "dependency-a 1.0\n"))
      (should (= exit-code 0)))))

(ert-deftest eldev-stable/unstable-4 ()
  (let ((eldev--test-project "missing-dependency-a"))
    (eldev--test-delete-cache)
    (eldev--test-run nil ("--setup" `(eldev-use-package-archive '(:stable   ("archive-a" . ,(expand-file-name "../package-archive-a"))
                                                                  :unstable ("archive-b" . ,(expand-file-name "../package-archive-b")))
                                                                '(0 . 0))
                          "--unstable" "version" "dependency-a")
      (should (string= stdout "dependency-a 1.1\n"))
      (should (= exit-code 0)))))

;; Real-world failure description: a project uses `melpa-unstable' archive and Buttercup
;; tests.  Before a fix got applied, Buttercup would also be installed from
;; `melpa-unstable', because that archive had been fetched already, so Eldev would try
;; with what it had, even if more prioritized `melpa-stable' had not been available.
(ert-deftest eldev-stable/unstable-5 ()
  (let ((eldev--test-project "missing-dependency-a"))
    (eldev--test-delete-cache)
    (eldev--test-run nil ("--setup" `(eldev-use-package-archive '("archive-b" . ,(expand-file-name "../package-archive-b")))
                          "prepare")
      (should (= exit-code 0)))
    (eldev--test-run nil ("--setup" `(eldev-use-package-archive '(:stable   ("archive-a" . ,(expand-file-name "../package-archive-a"))
                                                                  :unstable ("archive-b" . ,(expand-file-name "../package-archive-b"))))
                          "--setup" `(eldev-add-extra-dependencies 'eval 'dependency-b)
                          "eval" 1)
      (should (= exit-code 0)))
    (eldev--test-run nil ("--setup" `(eldev-add-extra-dependencies 'eval 'dependency-b)
                          "version" "dependency-b")
      (should (string= stdout "dependency-b 1.0\n"))
      (should (= exit-code 0)))))

;; Like the previous test, but with one more archive.  In real use this would be GNU ELPA.
(ert-deftest eldev-stable/unstable-6 ()
  (let ((eldev--test-project "missing-dependency-a"))
    (eldev--test-delete-cache)
    (eldev--test-run nil ("--setup" `(eldev-use-package-archive '("archive-d" . ,(expand-file-name "../package-archive-d")) 300)
                          "--setup" `(eldev-use-package-archive '("archive-b" . ,(expand-file-name "../package-archive-b")) 100)
                          "prepare")
      (should (= exit-code 0)))
    (eldev--test-run nil ("--setup" `(eldev-use-package-archive '("archive-d" . ,(expand-file-name "../package-archive-d")) 300)
                          "--setup" `(eldev-use-package-archive '(:stable   ("archive-a" . ,(expand-file-name "../package-archive-a"))
                                                                  :unstable ("archive-b" . ,(expand-file-name "../package-archive-b")))
                                                                100)
                          "--setup" `(eldev-add-extra-dependencies 'eval 'dependency-b)
                          "eval" 1)
      (should (= exit-code 0)))
    (eldev--test-run nil ("--setup" `(eldev-add-extra-dependencies 'eval 'dependency-b)
                          "version" "dependency-b")
      (should (string= stdout "dependency-b 1.0\n"))
      (should (= exit-code 0)))))


(ert-deftest eldev-stable/unstable-upgrade-1 ()
  (let ((eldev--test-project "project-h"))
    (eldev--test-delete-cache)
    (eldev--test-run nil ("version" "dependency-a")
      (should (string= stdout "dependency-a 1.0\n"))
      (should (= exit-code 0)))
    (eldev--test-run nil ("upgrade")
      (should (string= stdout "All dependencies are up-to-date\n"))
      (should (= exit-code 0)))
    (eldev--test-run nil ("version" "dependency-a")
      (should (string= stdout "dependency-a 1.0\n"))
      (should (= exit-code 0)))
    (eldev--test-run nil ("--unstable" "upgrade")
      (should (string= stdout "Upgraded or installed 1 dependency package\n"))
      (should (= exit-code 0)))
    (eldev--test-run nil ("version" "dependency-a")
      (should (string= stdout "dependency-a 1.1\n"))
      (should (= exit-code 0)))))

(ert-deftest eldev-stable/unstable-upgrade-2 ()
  (let ((eldev--test-project "project-h"))
    (eldev--test-delete-cache)
    (eldev--test-run nil ("--unstable" "version" "dependency-a")
      (should (string= stdout "dependency-a 1.1\n"))
      (should (= exit-code 0)))
    (eldev--test-run nil ("upgrade")
      (should (string= stdout "All dependencies are up-to-date\n"))
      (should (= exit-code 0)))
    (eldev--test-run nil ("version" "dependency-a")
      (should (string= stdout "dependency-a 1.1\n"))
      (should (= exit-code 0)))
    ;; It should be possible to downgrade back to the stable version with an option.
    (eldev--test-run nil ("upgrade" "--downgrade")
      (should (string= stdout "Upgraded or installed 1 dependency package\n"))
      (should (= exit-code 0)))
    (eldev--test-run nil ("version" "dependency-a")
      (should (string= stdout "dependency-a 1.0\n"))
      (should (= exit-code 0)))))


(provide 'test/archives)
