#! /bin/sh

# This script downloads Eldev startup script as `~/.eldev/bin/eldev'.

set -e


DIR=~/.eldev/bin

mkdir -p $DIR
curl -fsSL https://raw.githubusercontent.com/doublep/eldev/master/bin/eldev > $DIR/eldev
chmod a+x $DIR/eldev

echo "Eldev startup script has been installed."
echo "Don't forget to add \`$DIR' to PATH environment variable:"
echo
echo "    export PATH=\"$DIR:\$PATH\""
