#! /bin/sh

# This script downloads Emake startup script as `~/.emake/bin/emake'
# and EVM (Emacs Version Manager) for Travis CI.
#
# In your `.travis.yml' add this:
#
# - curl -fsSL https://raw.github.com/doublep/emake/master/webinstall/travis-emake-and-ert > x.sh && source ./x.sh

set -e


EMAKE_DIR=~/.emake/bin
EVM_DIR=~/.evm

export PATH="$EMAKE_DIR:$EVM_DIR:$PATH"

mkdir -p $EMAKE_DIR
curl -fsSL https://raw.githubusercontent.com/doublep/emake/master/bin/emake > $EMAKE_DIR/emake
chmod a+x $EMAKE_DIR/emake

git clone --depth 1 https://github.com/rejeep/evm.git $EVM_DIR
evm config path /tmp
