[#loading-modes]
== Loading modes

In Eldev the project’s package and its local dependencies have
_loading modes_.  This affects exactly how the package (that of the
project or of its local dependency) becomes loadable by Emacs.

Default loading mode is called `as-is`.  It means the directory where
project (or local dependency) is located is simply added to Emacs
varible `load-path` and normal Emacs loading should be able to find
required features from there on.  This is the fastest mode, since it
requires no preparation and in most cases is basically what you want
during development.

However, users won’t have your project loaded like that.  To emulate
the way that most of the people will use it, you can use loading mode
`packaged`.  In this mode, Eldev will first build a package out of
your project (or local dependency), then install and activate it using
Emacs’ packaging system.  This is quite a bit slower than `as-is`,
because it involves several preparation steps.  However, this is
almost exactly the way normal users will use your project after
e.g. installing it from MELPA.  For this reason, this mode is
recommended for <<continuous-integration,continuous integration>> and
other forms of automated testing.

Other modes include `byte-compiled` and `source`.  In these modes
loading is performed just as in `as-is` mode, but before that Eldev
either byte-compiles everything or, vice-versa, removes `.elc` files.

{since-1-4} Loading mode `compiled-on-demand` is useful primarily to
larger projects that include some computation-intensive code which
needs to be byte-compiled to run in reasonable time.  In this mode,
only when a project file is loaded, e.g. via `require` form, it is
byte-compiled if needed.  In contrast, in mode `byte-compiled` _all_
Elisp files are byte-compiled before a command (e.g. `test`) even gets
to start working.  This makes the mode useful during work on the
project “core” because 1) compilation time is reduced; 2) you can test
or otherwise use the core without even updating higher-level files to
be successfully compilable first.  However, as a drawback, compilation
can run “in the middle” of project’s real code, which can occasionally
cause unforeseen troubles, as well as screw up
<<profiling,profiling>>.

{since-1-7} Mode `noisy-compiled-on-demand` is basically the same,
with the only exception that Eldev prints a message (the same as
during normal compilation) when it decides to recompile something.  In
comparison, `compiled-on-demand` will only write to _stderr_ and only
if there are compilation warnings or errors.  Since having “random”
text inserted in normal program output is potentially disrupting,
especially if said output is processed by another tool, this is not
the default and you have to actively choose between
`compiled-on-demand` and `noisy-compiled-on-demand`.

When using <<evaluating,commands `exec` and `eval`>> with
`compiled-on-demand` mode, you may want to use option `-R`
(`--dont-require`) and then manually `require` only the necessary
features, to reduce the set of files that have to be (re)compiled.

So, after discussing various loading modes, let’s have a look at how
exactly you tell Eldev which one to use.

For the project itself, this is done from the command line using
global option `--loading` (or `-m`) with its argument being the name
of the mode.  Since this is supposed to be used quite frequently,
there are also shortcut options to select specific modes: `--as-is`
(or `-a`), `--packaged` (`-p`), `--source` (`-s`), `--byte-compiled`
(`-c`) and `--compiled-on-demand` (`-o`).  For example, the following
command will run unit-tests in the project, having it loaded as an
Emacs package:

    $ eldev -p test

Remember, that as everything in Eldev, this can be customized.
E.g. if you want to run your project byte-compiled by default, add
this to your `Eldev-local`:

[source]
----
(setf eldev-project-loading-mode 'byte-compiled)
----

For local dependencies the mode can be chosen when calling
`eldev-use-local-dependency`.  For example:

[source]
----
(eldev-use-local-dependency "~/barlib" 'packaged)
----

As mentioned above, loading mode defaults to `as-is`.

There are a few other loading modes useful only for certain projects.
You can always ask Eldev for a full list:

    $ eldev --list-modes

[#autoloads]
=== Autoloads

{since-0-6} Autoloaded functions of installed Elisp packages can be
accessed without a `require` form.  To simplify development, Eldev
provides the same functionality for projects regardless of loading
mode, as long as file `PACKAGE-autoloads.el` exists.  This might look
like an unwieldy requirement, but luckily there is
<<autoloads-plugin,a plugin>> for building the file and keeping it
up-to-date as necessary.  The reason this is not enabled by default is
that many projects — especially those not providing user-visible
functionality, or those that consist of a single file — don’t have any
autoloading functions or other forms.

Local dependencies also have their autoloads activated regardless of
loading mode.  If the autoloads file is kept up-to-date using
<<autoloads-plugin,the plugin>>, Eldev will take care to do this as
needed in local dependencies too.
